### ISSUE TITLE
ERROR: git repository not found at `..`

### ISSUE THREAD

**Issue by CSchoel** [JuliaRegistries/CompatHelper.jl#260]
Two months ago, CompatHelper started failing for my Package [ModelicaScriptingTools.jl](https://github.com/THM-MoTE/ModelicaScriptingTools.jl). The error message of the first failing run can be found here: https://github.com/THM-MoTE/ModelicaScriptingTools.jl/runs/1173990995

It seems that the first relevant line is `ERROR: git repository not found at '..'`. I am not sure what is even happening at this stage and why more than one repository needs to be cloned. I am also not very familiar with GitHub actions, so it is entirely possible that this is an error on my end. However, I cannot pinpoint any commit in this time that should have an effect on CompatHelper (apart from maybe an update to the Manifest.toml in the repository?), so I would greatly appreciate any help in debugging this issue.

Weirdly enough, I had two successful runs of CompatHelper three days ago, which coincided with the name change of the default branch from `master` to `main`, but now the newer runs fail again.

**Comment by DilumAluthge** [comment]
This might be due to a problem with one or more `Manifest.toml` files in your repo. Can you try deleting all `Manifest.toml` files from your repo, and then see if it fixes the problem.

I'm going to close this for now - if deleting all `Manifest.toml` files doesn't fix the issue, let me know, and I'll reopen this issue.
