### ISSUE TITLE
CompatHelper broken? 

### ISSUE THREAD

**Issue by baggepinnen** [JuliaRegistries/CompatHelper.jl#281]
The last 24hrs I've gotten hundreds of CompatHelper failures on all my packages and they all look like this one
https://github.com/baggepinnen/DynamicAxisWarping.jl/runs/2263090833?check_suite_focus=true
Has something happened the last day that could cause this?

**Comment by DilumAluthge** [comment]
So, in the last day or two, CompatHelper dropped support for Julia < 1.5. But CompatHelper also updated its `[compat]` entry for Julia, so the Pkg resolver shouldn't try to install newer versions of CompatHelper on old versions of Julia if the newer version of CompatHelper is not compatible with the old version of Julia.

But when a package is added by URL, I think that Pkg ignores Julia version incompatibilities, and always just installs the latest `master` branch of the package, even if the latest `master` branch of the package is not compatible with the version of Julia that is running.

So, looking at https://github.com/baggepinnen/DynamicAxisWarping.jl/blob/master/.github/workflows/CompatHelper.yml, I think this is what happened:
1. The workflow file installs an old version of Julia (1.2.0).
2. The workflow file installs CompatHelper by URL.
3. Even though the `master` branch of CompatHelper explicitly says that it is not compatible with Julia 1.2.0, Pkg installs the `master` branch anyway.

The changes that need to be made to the workflow file include:
1. There is no need to install Julia. Julia is available by default in the GitHub Actions runners.
2. CompatHelper should be installed by name and UUID. It should not be installed by URL.

Can you update the `.github/workflows/CompatHelper.yml` files in all of your repos so that the contents of that file exactly match the contents of [https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml](https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml)? This should fix the problems.

Let me know if you still run into problems even after you do that.

**Comment by DilumAluthge** [comment]
@baggepinnen Did updating the `.github/workflows/CompatHelper.yml` files fix the issue?

**Comment by baggepinnen** [comment]
Yep, appears to be a good solution. Thanks for the explanation!
